-- V5: User-data cloud sync (Tarea 59 / ONE-27)
-- Six tables holding everything the Flutter client today stores locally
-- in ObjectBox + SharedPreferences, so the user can switch devices and
-- keep their solves, sessions, preferences, profile, learned algorithms
-- and unlocked avatars.
--
-- Lives in the `auth` schema next to `users`. All tables FK to
-- `auth.users(id)` with ON DELETE CASCADE so deleting a user cleans up
-- everything in one shot.

-- ── Solves ────────────────────────────────────────────────────────────────
CREATE TABLE user_solves (
    id                  BIGSERIAL    PRIMARY KEY,
    user_id             BIGINT       NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    client_id           VARCHAR(64)  NOT NULL,            -- UUID generated by client, idempotency key
    session_client_id   VARCHAR(64),                      -- soft FK to user_sessions.client_id (string, not enforced FK)
    solve_time_ms       INTEGER      NOT NULL,
    solved_at           TIMESTAMPTZ,
    scramble            TEXT,
    scramble_image_svg  TEXT,
    is_ok               BOOLEAN      NOT NULL DEFAULT TRUE,
    has_plus2           BOOLEAN      NOT NULL DEFAULT FALSE,
    has_dnf             BOOLEAN      NOT NULL DEFAULT FALSE,
    is_favorite         BOOLEAN      NOT NULL DEFAULT FALSE,
    is_deleted          BOOLEAN      NOT NULL DEFAULT FALSE,
    comments            TEXT,
    created_at          TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_user_solves_client UNIQUE (user_id, client_id)
);
CREATE INDEX idx_user_solves_user_updated ON user_solves (user_id, updated_at);
CREATE INDEX idx_user_solves_user_session ON user_solves (user_id, session_client_id);

-- ── Sessions ──────────────────────────────────────────────────────────────
CREATE TABLE user_sessions (
    id           BIGSERIAL    PRIMARY KEY,
    user_id      BIGINT       NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    client_id    VARCHAR(64)  NOT NULL,
    name         TEXT         NOT NULL,
    category_id  VARCHAR(32)  NOT NULL,                  -- e.g. '333', '222'
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at   TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_user_sessions_client UNIQUE (user_id, client_id)
);
CREATE INDEX idx_user_sessions_user ON user_sessions (user_id);

-- ── Preferences ───────────────────────────────────────────────────────────
-- Single JSONB column instead of 20+ typed columns. The contract is
-- between client and self: the server never filters by a preference.
-- Avoids future migrations every time the app adds a new toggle.
CREATE TABLE user_preferences (
    user_id      BIGINT       PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    preferences  JSONB        NOT NULL DEFAULT '{}'::jsonb,
    updated_at   TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

-- ── Profile ───────────────────────────────────────────────────────────────
-- Currently only stores the user-chosen displayName. Validated against
-- the WCA name in users.name on PUT.
CREATE TABLE user_profile (
    user_id                  BIGINT       PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    display_name             TEXT,                          -- null = use the WCA name verbatim
    display_name_updated_at  TIMESTAMPTZ,
    updated_at               TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

-- ── Learned algorithms ────────────────────────────────────────────────────
CREATE TABLE user_learned_algorithms (
    id            BIGSERIAL    PRIMARY KEY,
    user_id       BIGINT       NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    case_id       VARCHAR(64)  NOT NULL,
    submethod_id  VARCHAR(64)  NOT NULL,
    learned_at    TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_user_learn UNIQUE (user_id, case_id, submethod_id)
);
CREATE INDEX idx_user_learn_user ON user_learned_algorithms (user_id);

-- ── Avatars ───────────────────────────────────────────────────────────────
-- Denormalized (name/description/rarity stored alongside avatar_id) so
-- a single GET doesn't need to join the catalog table that the avatar
-- system (Tarea 14 / ONE-14) will eventually own.
CREATE TABLE user_avatars (
    id           BIGSERIAL    PRIMARY KEY,
    user_id      BIGINT       NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    avatar_id    VARCHAR(64)  NOT NULL,
    name         TEXT,
    description  TEXT,
    rarity       INTEGER      NOT NULL DEFAULT 0,
    unlocked_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_user_avatars UNIQUE (user_id, avatar_id)
);
CREATE INDEX idx_user_avatars_user ON user_avatars (user_id);
